# Generated by Django 5.1.4 on 2026-03-19 20:30

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.CharField(default=api.models.generate_id, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'brands',
            },
        ),
        migrations.CreateModel(
            name='BrushHairType',
            fields=[
                ('id', models.CharField(default=api.models.generate_id, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'brush_hair_types',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.CharField(default=api.models.generate_id, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('hex_code', models.CharField(blank=True, max_length=7)),
            ],
            options={
                'db_table': 'colors',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.CharField(default=api.models.generate_id, max_length=36, primary_key=True, serialize=False)),
                ('original_file_name', models.CharField(max_length=500)),
                ('url_path', models.URLField(blank=True, max_length=1000)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'files',
            },
        ),
        migrations.CreateModel(
            name='PaperMaterial',
            fields=[
                ('id', models.CharField(default=api.models.generate_id, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'paper_materials',
            },
        ),
        migrations.CreateModel(
            name='PaperSurface',
            fields=[
                ('id', models.CharField(default=api.models.generate_id, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'paper_surfaces',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.CharField(default=api.models.generate_id, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'stores',
            },
        ),
        migrations.CreateModel(
            name='ToolShape',
            fields=[
                ('id', models.CharField(default=api.models.generate_id, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tool_shapes',
            },
        ),
        migrations.CreateModel(
            name='ToolSize',
            fields=[
                ('id', models.CharField(default=api.models.generate_id, max_length=36, primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tool_sizes',
            },
        ),
        migrations.CreateModel(
            name='ToolType',
            fields=[
                ('id', models.CharField(default=api.models.generate_id, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tool_types',
            },
        ),
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.CharField(default=api.models.generate_id, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='api.brand')),
            ],
            options={
                'db_table': 'brand_models',
            },
        ),
        migrations.CreateModel(
            name='Paint',
            fields=[
                ('id', models.CharField(default=api.models.generate_id, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(0, 'Acrylic'), (1, 'WaterColor'), (2, 'Oil'), (3, 'Gouache'), (4, 'Ink'), (5, 'Pastel')])),
                ('ref_paint', models.CharField(blank=True, max_length=255)),
                ('ref_brand_color', models.CharField(blank=True, max_length=255)),
                ('granulating', models.BooleanField(blank=True, null=True)),
                ('staining', models.BooleanField(blank=True, null=True)),
                ('opacity', models.IntegerField(blank=True, choices=[(0, 'Opaque'), (1, 'SemiOpaque'), (2, 'Semi'), (3, 'SemiTransparent'), (4, 'Transparent')], null=True)),
                ('opacity_number', models.IntegerField(blank=True, null=True)),
                ('quality', models.IntegerField(blank=True, choices=[(0, 'ArtistsGrade'), (1, 'StudentGrade')], null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paints', to='api.brand')),
                ('brand_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paints', to='api.brandmodel')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paints', to='api.color')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paint_images', to='api.file')),
            ],
            options={
                'db_table': 'paints',
            },
        ),
        migrations.CreateModel(
            name='Pigment',
            fields=[
                ('id', models.CharField(default=api.models.generate_id, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pigments', to='api.color')),
            ],
            options={
                'db_table': 'pigments',
            },
        ),
        migrations.CreateModel(
            name='PigmentPaint',
            fields=[
                ('id', models.CharField(default=api.models.generate_id, max_length=36, primary_key=True, serialize=False)),
                ('paint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pigment_paints', to='api.paint')),
                ('pigment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pigment_paints', to='api.pigment')),
            ],
            options={
                'db_table': 'pigment_paints',
                'unique_together': {('paint', 'pigment')},
            },
        ),
        migrations.AddField(
            model_name='paint',
            name='pigments',
            field=models.ManyToManyField(related_name='paints', through='api.PigmentPaint', to='api.pigment'),
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.CharField(default=api.models.generate_id, max_length=36, primary_key=True, serialize=False)),
                ('gsm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ref', models.CharField(blank=True, max_length=255)),
                ('original_size', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('verbose_name', models.CharField(blank=True, max_length=500)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers', to='api.brand')),
                ('brand_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers', to='api.brandmodel')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers', to='api.color')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_images', to='api.file')),
                ('paper_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers', to='api.papermaterial')),
                ('paper_surface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers', to='api.papersurface')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers', to='api.store')),
            ],
            options={
                'db_table': 'papers',
            },
        ),
        migrations.AddField(
            model_name='paint',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paints', to='api.store'),
        ),
        migrations.CreateModel(
            name='Stroke',
            fields=[
                ('id', models.CharField(default=api.models.generate_id, max_length=36, primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('image_100', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stroke_img100', to='api.file')),
                ('image_1800', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stroke_img1800', to='api.file')),
                ('image_2500', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stroke_img2500', to='api.file')),
                ('image_600', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stroke_img600', to='api.file')),
                ('image_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stroke_imgoriginal', to='api.file')),
                ('paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strokes', to='api.paper')),
            ],
            options={
                'db_table': 'strokes',
                'ordering': ['order_id'],
            },
        ),
        migrations.CreateModel(
            name='StrokePaint',
            fields=[
                ('id', models.CharField(default=api.models.generate_id, max_length=36, primary_key=True, serialize=False)),
                ('paint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stroke_paints', to='api.paint')),
                ('stroke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stroke_paints', to='api.stroke')),
            ],
            options={
                'db_table': 'stroke_paints',
            },
        ),
        migrations.AddField(
            model_name='stroke',
            name='paints',
            field=models.ManyToManyField(related_name='strokes', through='api.StrokePaint', to='api.paint'),
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.CharField(default=api.models.generate_id, max_length=36, primary_key=True, serialize=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('quality', models.IntegerField(blank=True, choices=[(0, 'ArtistsGrade'), (1, 'StudentGrade')], null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='api.brand')),
                ('brush_hair_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='api.brushhairtype')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_images', to='api.file')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='api.brandmodel')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='api.store')),
                ('shape', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='api.toolshape')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='api.toolsize')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='api.tooltype')),
            ],
            options={
                'db_table': 'tools',
            },
        ),
        migrations.CreateModel(
            name='StrokeTool',
            fields=[
                ('id', models.CharField(default=api.models.generate_id, max_length=36, primary_key=True, serialize=False)),
                ('stroke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stroke_tools', to='api.stroke')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stroke_tools', to='api.tool')),
            ],
            options={
                'db_table': 'stroke_tools',
            },
        ),
        migrations.AddField(
            model_name='stroke',
            name='tools',
            field=models.ManyToManyField(related_name='strokes', through='api.StrokeTool', to='api.tool'),
        ),
        migrations.AddField(
            model_name='toolsize',
            name='tool_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='api.tooltype'),
        ),
        migrations.AddField(
            model_name='toolshape',
            name='tool_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shapes', to='api.tooltype'),
        ),
    ]
