# Generated by Django 5.1.4 on 2026-04-19 19:41

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('token', models.CharField(default=api.models.generate_device_token, editable=False, max_length=64)),
                ('desired_git_ref', models.CharField(default='main', max_length=64)),
                ('last_reported_ref', models.CharField(blank=True, max_length=64)),
                ('last_status', models.CharField(choices=[('ok', 'OK'), ('updating', 'Updating'), ('failed', 'Failed'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('last_error', models.TextField(blank=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('last_update_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'devices',
                'ordering': ['id'],
            },
        ),
    ]
