# Generated by Django 5.1.4 on 2026-04-19 20:52

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_device'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifyJob',
            fields=[
                ('id', models.CharField(default=api.models.generate_id, max_length=36, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('repo', models.CharField(default='mgpepe/perfect-stroke-project-epaper', max_length=200)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('testing', 'Testing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('current_phase', models.CharField(blank=True, choices=[('', '—'), ('cloning', 'Cloning'), ('editing', 'Editing'), ('testing', 'Testing'), ('correcting', 'Correcting'), ('committing', 'Committing'), ('pushing', 'Pushing')], default='', max_length=16)),
                ('round_num', models.IntegerField(default=0)),
                ('max_rounds', models.IntegerField(default=3)),
                ('cost_usd', models.FloatField(default=0.0)),
                ('max_cost_usd', models.FloatField(default=200.0)),
                ('model', models.CharField(default='claude-opus-4-7', max_length=64)),
                ('commit_sha', models.CharField(blank=True, default='', max_length=64)),
                ('branch', models.CharField(default='main', max_length=64)),
                ('diff', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('log', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modify_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'modify_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='modify_jobs_created_bf3ca1_idx'), models.Index(fields=['status'], name='modify_jobs_status_1bb45a_idx')],
            },
        ),
    ]
