# Generated by Django 5.1.4 on 2026-04-19 20:53

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_modify_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.CharField(default=api.models.generate_id, max_length=36, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contacts',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.CharField(default=api.models.generate_id, max_length=36, primary_key=True, serialize=False)),
                ('sold_at', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='api.contact')),
                ('stroke', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='api.stroke')),
            ],
            options={
                'db_table': 'sales',
                'ordering': ['-sold_at', '-created_at'],
            },
        ),
    ]
