# Generated by Django 5.1.4 on 2026-04-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_contact_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifyjob',
            name='max_rounds',
            field=models.IntegerField(default=10),
        ),
    ]
