# Generated by Django 5.1.4 on 2026-04-19 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_modifyjob_rounds_10'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='price',
        ),
    ]
