# Generated by Django 5.1.4 on 2026-04-19 21:41

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_sale_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='WifiNetwork',
            fields=[
                ('id', models.CharField(default=api.models.generate_id, max_length=36, primary_key=True, serialize=False)),
                ('ssid', models.CharField(max_length=64)),
                ('password', models.CharField(blank=True, help_text='Leave empty for open networks.', max_length=128)),
                ('priority', models.IntegerField(default=50, help_text='Higher wins when multiple networks are reachable (NM autoconnect-priority).')),
                ('country', models.CharField(default='BG', help_text='Two-letter country code (regulatory domain).', max_length=2)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wifi_networks', to='api.device')),
            ],
            options={
                'db_table': 'wifi_networks',
                'ordering': ['-priority', 'ssid'],
                'unique_together': {('device', 'ssid')},
            },
        ),
    ]
